version: 2

jobs:
  deploy_to_test:
    machine:
      enabled: true
    working_directory: ~/public
    environment:
      HEROKU_APP_NAME: 'typing-joakim-test'
    steps:
      - checkout
      - run:
          name: Deploy to test server
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_TEST_ENV.git master

  deploy_to_prod:
    machine:
      enabled: true
    working_directory: ~/public
    environment:
      HEROKU_APP_NAME: 'typing-joakim-test-prod'
    steps:
      - checkout
      - run:
          name: Deploy to production server
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROD_ENV.git master

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy_to_test:
          filters:
            branches:
              only: feature/0-Hackathon
      - deploy_to_prod:
          filters:
            branches:
              only: master
